export const REQUEST_SERVICES_LIST = 'REQUEST_SERVICES_LIST';
export const SUCCES_REQUEST_SERVICES_LIST = 'SUCCES_REQUEST_SERVICES_LIST';
export const ERROR_REQUEST_SERVICES_LIST = 'ERROR_REQUEST_SERVICES_LIST';