export const REQUEST_SERVICES_LIST = 'REQUEST_SERVICES_LIST';
export const SUCCES_REQUEST_SERVICES_LIST = 'SUCCES_REQUEST_SERVICES_LIST';
export const ERROR_REQUEST_SERVICES_LIST = 'ERROR_REQUEST_SERVICES_LIST';

export const REQUEST_SERVICE = 'REQUEST_SERVICE';
export const SUCCES_REQUEST_SERVICE = 'SUCCES_REQUEST_SERVICE';
export const ERROR_REQUEST_SERVICE = 'ERROR_REQUEST_SERVICE';